### ISSUE TITLE
URI is not valid and cannot be converted into a string

### ISSUE THREAD

**Issue by asmitarane** [zendframework/zend-uri#15]
Please, anyone, help me to resolve this error.

a:4:{i:0;s:54:"URI is not valid and cannot be converted into a string";i:1;s:1717:"#0 /home/magento/public_html/voylite/vendor/zendframework/zend-http/src/Header/AbstractLocation.php(98): Zend\Uri\Uri->toString()
#1 /home/magento/public_html/voylite/vendor/zendframework/zend-http/src/Header/AbstractLocation.php(133): Zend\Http\Header\AbstractLocation->getUri()
#2 /home/magento/public_html/voylite/vendor/zendframework/zend-http/src/PhpEnvironment/Response.php(98): Zend\Http\Header\AbstractLocation->toString()
#3 /home/magento/public_html/voylite/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(310): Zend\Http\PhpEnvironment\Response->sendHeaders()
#4 /home/magento/public_html/voylite/vendor/zendframework/zend-http/src/PhpEnvironment/Response.php(128): Magento\Framework\App\Response\Http\Interceptor->sendHeaders()
#5 /home/magento/public_html/voylite/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(336): Zend\Http\PhpEnvironment\Response->send()
#6 /home/magento/public_html/voylite/vendor/magento/framework/HTTP/PhpEnvironment/Response.php(44): Magento\Framework\App\Response\Http\Interceptor->send()
#7 /home/magento/public_html/voylite/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\HTTP\PhpEnvironment\Response->sendResponse()
#8 /home/magento/public_html/voylite/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array)
#9 /home/magento/public_html/voylite/vendor/magento/framework/App/Bootstrap.php(259): Magento\Framework\App\Response\Http\Interceptor->sendResponse()
#10 /home/magento/public_html/voylite/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#11 {main}";s:3:"url";s:93:"/voylite/checkout/cart/add/uenc/aHR0cDovL21hZ2VudG8ud2F0c21vLmNvbS92b3lsaXRlLw,,/product/117/";s:11:"script_name";s:18:"/voylite/index.php";}

**Comment by froschdesign** [comment]
@asmitarane 
Sorry, but nobody can see your URI and without an URI we can not help.
Perhaps it is an error in your "Magento" shop configuration.

**Comment by asmitarane** [comment]
I have copy paste my error above

**Comment by asmitarane** [comment]
The URI is:
http://205.147.100.198/voylite/checkout/cart/add/uenc/aHR0cDovLzIwNS4xNDcuMTAwLjE5OC92b3lsaXRlLw,,/product/336/

**Comment by froschdesign** [comment]
@asmitarane 
No problem with zend-uri:

```php
$uri = new Zend\Uri\Http(
    'http://205.147.100.198/voylite/checkout/cart/add/uenc/aHR0cDovLzIwNS4xNDcuMTAwLjE5OC92b3lsaXRlLw,,/product/336/'
);
var_dump($uri->toString());
// Output: http://205.147.100.198/voylite/checkout/cart/add/uenc/aHR0cDovLzIwNS4xNDcuMTAwLjE5OC92b3lsaXRlLw,,/product/336/
```

and zend-http:

```php
$location = new \Zend\Http\Header\Location();
$location->setUri(
    'http://205.147.100.198/voylite/checkout/cart/add/uenc/aHR0cDovLzIwNS4xNDcuMTAwLjE5OC92b3lsaXRlLw,,/product/336/'
);
var_dump($location->toString());
// Output: Location: http://205.147.100.198/voylite/checkout/cart/add/uenc/aHR0cDovLzIwNS4xNDcuMTAwLjE5OC92b3lsaXRlLw,,/product/336/
```
**I see no problem with Zend Framework.**

Please debug your "Magento" application and which URI is set. Then ask at a "Magento" forum or bugtracker.

**Comment by asmitarane** [comment]
I have used the theme and customised that theme as per requirement.

theme link: http://magento2.flytheme.net/themes/sm_revo/default

My site link: http://205.147.100.198/voylite/

**Comment by froschdesign** [comment]
@asmitarane 
Sorry, but this is the wrong issue tracker for Magento! Use: https://magento.com/tech-resources/bug-tracking/

**Comment by asmitarane** [comment]
thanks @francisdaigle

**Comment by asmitarane** [comment]
I am not able add to cart product from home page only

**Comment by froschdesign** [comment]
@asmitarane 
**It is still Magento problem and not a problem of Zend Framework.**

https://magento.com/tech-resources/bug-tracking/ is the right place to submit your problems!

I am very sorry, but I will lock the conversation at this point.
