### ISSUE TITLE
Failed to download zendframework/zend-uri

### ISSUE THREAD

**Issue by devtosystems** [zendframework/zend-uri#8]
- Installing zendframework/zend-uri (dev-develop ed906be)
    Failed to download zendframework/zend-uri from source: Could not delete /home/vagrant/projects/web/zf2/opevere/vendor/zendframework/zend-uri/.git/objects/pack/tmp_pack_9zExI7:
    Now trying to download from dist

**Comment by weierophinney** [comment]
Check the permissions of your vendor directory. If you continue to have problems, please report to the composer project.
